# fly.toml app configuration file generated for art-project-alu on 2025-04-02T16:35:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'art-project-alu'
primary_region = 'cdg'

[build]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024