# fly.toml app configuration file generated for art-project-alu on 2025-04-02T16:35:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'art-project-alu'
primary_region = 'cdg'

[build]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[env]
  PORT = "3000"
  NODE_ENV = "production"